spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://134.0.115.15:5432/geoprofit
    username: postgres
    password: "postgres"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: DEBUG

